# Generated by Django 5.2.11 on 2026-02-13 17:49

import apps.candidates.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.candidates.models.candidate_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.post')),
            ],
            options={
                'ordering': ['post', 'name'],
                'unique_together': {('post', 'name')},
            },
        ),
    ]
