# Generated by Django 5.2.11 on 2026-02-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['post', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
