# Generated by Django 5.2.11 on 2026-02-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_securityquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('verification_code_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('resend_attempts', models.IntegerField(default=0)),
                ('next_resend_available_at', models.DateTimeField(blank=True, null=True)),
                ('security_questions_verified', models.BooleanField(default=False)),
                ('code_verified', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'created_at'], name='accounts_pa_email_610545_idx')],
            },
        ),
    ]
