# Generated by Django 5.2.5 on 2026-02-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_email_last_changed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_password_reset_request',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password_reset_expiration',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password_reset_token_hash',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='token_expiration',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_code_hash',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_token_hash',
        ),
    ]
