# Generated by Django 5.2.11 on 2026-02-20 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('max_elections', models.PositiveIntegerField(default=5)),
                ('max_active_elections', models.PositiveIntegerField(default=2)),
                ('max_posts_per_election', models.PositiveIntegerField(default=5)),
                ('max_candidates_per_post', models.PositiveIntegerField(default=10)),
                ('max_voters_per_election', models.PositiveIntegerField(default=100)),
                ('max_voters_per_import', models.PositiveIntegerField(default=50)),
                ('can_export_pdf', models.BooleanField(default=True)),
                ('can_use_offline_credentials', models.BooleanField(default=False)),
                ('can_view_blockchain_audit', models.BooleanField(default=True)),
                ('can_use_custom_branding', models.BooleanField(default=False)),
                ('priority_email_delivery', models.BooleanField(default=False)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('badge_color', models.CharField(default='apple-blue', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_provider', models.CharField(blank=True, default='', max_length=30)),
                ('payment_customer_id', models.CharField(blank=True, default='', max_length=100)),
                ('payment_subscription_id', models.CharField(blank=True, default='', max_length=100)),
                ('plan_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='subscriptions.subscriptionplan')),
                ('previous_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='subscriptions.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
