# Generated by Django 5.2.11 on 2026-02-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_seed_default_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
