# Generated by Django 5.2.11 on 2026-02-13 17:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=255)),
                ('is_launched', models.BooleanField(default=False)),
                ('is_paused', models.BooleanField(default=False)),
                ('is_terminated_by_admin', models.BooleanField(default=False)),
                ('launch_time', models.DateTimeField(blank=True, null=True)),
                ('allow_voter_results_view', models.BooleanField(default=False)),
                ('allow_abstain', models.BooleanField(default=False, help_text='Allow voters to abstain/skip individual posts.')),
                ('admin_message', models.TextField(blank=True, default='')),
                ('access_code', models.CharField(blank=True, db_index=True, default='', help_text='Short access code for voter-friendly election URL.', max_length=8)),
                ('blockchain_contract_address', models.CharField(blank=True, default='', max_length=42)),
                ('blockchain_deploy_tx', models.CharField(blank=True, default='', max_length=66)),
                ('config_hash', models.CharField(blank=True, default='', max_length=66)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('allow_abstain', models.BooleanField(blank=True, default=None, help_text='Override election-level abstain setting for this post. None = inherit.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='elections.election')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['created_by', '-created_at'], name='elections_e_created_419db5_idx'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['election_uuid'], name='elections_e_electio_d415ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('election', 'name')},
        ),
    ]
