# Generated by Django 5.2.5 on 2026-02-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='setup_step',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
