# Generated by Django 5.2.11 on 2026-02-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_add_setup_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='blockchain_contract_address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='election',
            name='blockchain_deploy_tx',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
