# Generated by Django 5.2.5 on 2026-02-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_cleanup_setup_step_and_voter_results'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='election',
            name='elections_e_electio_d415ae_idx',
        ),
    ]
