# Generated by Django 5.2.11 on 2026-02-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_remove_election_elections_e_electio_d415ae_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('online', 'Online'), ('onsite', 'Onsite'), ('hybrid', 'Hybrid')], default='online', help_text='Online: email invitations only. Onsite: offline credentials only. Hybrid: both.', max_length=10),
        ),
    ]
