# Generated by Django 5.2.11 on 2026-02-25 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_remove_pause_terminate_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='election',
            constraint=models.UniqueConstraint(condition=models.Q(('access_code', ''), _negated=True), fields=('access_code',), name='unique_nonempty_access_code'),
        ),
    ]
