# Generated by Django 5.2.11 on 2026-02-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_add_unique_access_code_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='election_type',
        ),
    ]
