# Generated by Django 5.2.11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0009_remove_election_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='allow_abstain',
        ),
    ]
