# Generated by Django 5.2.11 on 2026-02-13 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=42, unique=True)),
                ('deploy_tx_hash', models.CharField(max_length=66)),
                ('deploy_block', models.PositiveIntegerField()),
                ('network', models.CharField(choices=[('polygon', 'Polygon Mainnet'), ('amoy', 'Polygon Amoy Testnet')], max_length=20)),
                ('abi_version', models.CharField(default='1.0', max_length=10)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_deployment', to='elections.election')),
            ],
            options={
                'db_table': 'blockchain_contract_deployment',
                'ordering': ['-deployed_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('deploy', 'Deploy Contract'), ('register_voter', 'Register Voter'), ('register_voters_batch', 'Register Voters (Batch)'), ('add_candidate', 'Add Candidate'), ('cast_vote', 'Cast Vote'), ('pause', 'Pause Election'), ('resume', 'Resume Election')], max_length=30)),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('block_number', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('gas_used', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_transactions', to='elections.election')),
            ],
            options={
                'db_table': 'blockchain_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['election', 'tx_type'], name='blockchain__electio_6dc819_idx'), models.Index(fields=['status', 'created_at'], name='blockchain__status_f05873_idx')],
            },
        ),
    ]
