# Generated by Django 5.2.11 on 2026-02-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchaintransaction',
            name='block_number',
        ),
        migrations.RemoveField(
            model_name='blockchaintransaction',
            name='gas_used',
        ),
        migrations.RemoveField(
            model_name='blockchaintransaction',
            name='tx_hash',
        ),
        migrations.RemoveField(
            model_name='contractdeployment',
            name='abi_version',
        ),
        migrations.RemoveField(
            model_name='contractdeployment',
            name='contract_address',
        ),
        migrations.RemoveField(
            model_name='contractdeployment',
            name='deploy_block',
        ),
        migrations.RemoveField(
            model_name='contractdeployment',
            name='deploy_tx_hash',
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='compute_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='slot',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='tx_signature',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='contractdeployment',
            name='deploy_slot',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractdeployment',
            name='deploy_tx_signature',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contractdeployment',
            name='program_address',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='blockchaintransaction',
            name='tx_type',
            field=models.CharField(choices=[('deploy', 'Deploy Election'), ('register_voters', 'Register Voters'), ('cast_vote', 'Cast Vote')], max_length=30),
        ),
        migrations.AlterField(
            model_name='contractdeployment',
            name='network',
            field=models.CharField(choices=[('devnet', 'Solana Devnet'), ('mainnet-beta', 'Solana Mainnet Beta')], max_length=20),
        ),
    ]
