# Generated by Django 5.2.11 on 2026-03-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_blockchainarchive_txtype_finalize_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdeployment',
            name='network',
            field=models.CharField(choices=[('localnet', 'Solana Localnet (test-validator)'), ('devnet', 'Solana Devnet'), ('testnet', 'Solana Testnet'), ('mainnet-beta', 'Solana Mainnet Beta')], max_length=20),
        ),
    ]
