# Generated by Django 5.2.11 on 2026-02-13 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login_success', 'Login Success'), ('login_failure', 'Login Failure'), ('logout', 'Logout'), ('register', 'Register'), ('password_reset', 'Password Reset'), ('password_change', 'Password Change'), ('election_create', 'Election Created'), ('election_launch', 'Election Launched'), ('election_end', 'Election Ended'), ('election_pause', 'Election Paused'), ('election_resume', 'Election Resumed'), ('election_delete', 'Election Deleted'), ('election_update', 'Election Updated'), ('vote_cast', 'Vote Cast'), ('voter_registered', 'Voter Registered'), ('voter_revoked', 'Voter Revoked'), ('voter_import', 'Voters Imported'), ('account_delete', 'Account Deleted'), ('account_update', 'Account Updated')], db_index=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='elections.election')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx'), models.Index(fields=['user', 'action'], name='audit_audit_user_id_ac289d_idx'), models.Index(fields=['election', 'action'], name='audit_audit_electio_5d100e_idx')],
            },
        ),
    ]
