# Generated by Django 5.2.11 on 2026-02-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failure', 'Login Failure'), ('logout', 'Logout'), ('register', 'Register'), ('password_reset', 'Password Reset'), ('password_change', 'Password Change'), ('election_create', 'Election Created'), ('election_launch', 'Election Launched'), ('election_end', 'Election Ended'), ('election_delete', 'Election Deleted'), ('election_update', 'Election Updated'), ('vote_cast', 'Vote Cast'), ('voter_registered', 'Voter Registered'), ('voter_revoked', 'Voter Revoked'), ('voter_import', 'Voters Imported'), ('account_delete', 'Account Deleted'), ('account_update', 'Account Updated')], db_index=True, max_length=30),
        ),
    ]
