# Generated by Django 5.2.11 on 2026-02-13 17:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('voter_hash', models.CharField(help_text='SHA-256(credential_id:election_id:salt) — cannot be reversed', max_length=64)),
                ('blockchain_tx_hash', models.CharField(blank=True, default='', max_length=66)),
                ('blockchain_block', models.PositiveIntegerField(blank=True, null=True)),
                ('blockchain_confirmed', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='candidates.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.election')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.post')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['election', 'post', 'candidate'], name='voting_vote_electio_e43ffc_idx'), models.Index(fields=['voter_hash'], name='voting_vote_voter_h_78be00_idx')],
                'unique_together': {('election', 'post', 'voter_hash')},
            },
        ),
        migrations.CreateModel(
            name='VoterCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_email', models.EmailField(max_length=254)),
                ('voter_name', models.CharField(blank=True, default='', max_length=255)),
                ('one_time_username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('one_time_password_hash', models.CharField(max_length=255)),
                ('has_voted', models.BooleanField(default=False)),
                ('is_revoked', models.BooleanField(default=False)),
                ('invitation_sent', models.BooleanField(default=False)),
                ('invitation_error', models.TextField(blank=True, default='')),
                ('blockchain_secret', models.BinaryField(blank=True, max_length=32, null=True)),
                ('blockchain_voter_hash', models.CharField(blank=True, default='', max_length=66)),
                ('blockchain_registered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_credentials', to='elections.election')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['one_time_username'], name='voting_vote_one_tim_ec86b9_idx'), models.Index(fields=['election', 'has_voted'], name='voting_vote_electio_557866_idx'), models.Index(fields=['election', 'voter_email'], name='voting_vote_electio_452ee7_idx'), models.Index(fields=['election', 'invitation_sent'], name='voting_vote_electio_0a351a_idx')],
                'unique_together': {('election', 'voter_email')},
            },
        ),
    ]
