# Generated by Django 5.2.11 on 2026-02-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='blockchain_block',
        ),
        migrations.AddField(
            model_name='vote',
            name='blockchain_slot',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
