# Generated by Django 5.2.5 on 2026-02-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_remove_vote_blockchain_block_vote_blockchain_slot_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='votercredential',
            name='voting_vote_one_tim_ec86b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='votercredential',
            name='voting_vote_electio_452ee7_idx',
        ),
        migrations.AlterField(
            model_name='votercredential',
            name='one_time_username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
