# Generated by Django 5.2.11 on 2026-02-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_add_candidate_order'),
        ('elections', '0009_remove_election_type'),
        ('voting', '0003_remove_votercredential_voting_vote_one_tim_ec86b9_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='votercredential',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='votercredential',
            name='batch_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='votercredential',
            name='credentials_resent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='votercredential',
            name='invited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='votercredential',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='votercredential',
            name='voted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='votercredential',
            name='blockchain_secret',
            field=models.BinaryField(blank=True, max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('election', 'post', 'voter_hash'), name='unique_vote_per_post'),
        ),
        migrations.AddConstraint(
            model_name='votercredential',
            constraint=models.UniqueConstraint(fields=('election', 'voter_email'), name='unique_voter_per_election'),
        ),
    ]
