# Generated by Django 5.2.11 on 2026-02-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0009_remove_election_type'),
        ('voting', '0005_votercredential_blockchain_voter_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votercredential',
            name='blockchain_registered',
        ),
        migrations.RemoveField(
            model_name='votercredential',
            name='blockchain_secret',
        ),
        migrations.AlterField(
            model_name='votercredential',
            name='blockchain_voter_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='votercredential',
            index=models.Index(fields=['election', 'blockchain_voter_hash'], name='idx_cred_bc_hash'),
        ),
        migrations.AddConstraint(
            model_name='votercredential',
            constraint=models.UniqueConstraint(condition=models.Q(('blockchain_voter_index__isnull', False)), fields=('election', 'blockchain_voter_index'), name='unique_voter_index_per_election'),
        ),
    ]
