# Generated by Django 5.2.11 on 2026-02-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_remove_dead_fields_add_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='votercredential',
            name='invitation_error_code',
            field=models.CharField(blank=True, choices=[('INVALID_FORMAT', 'Invalid email address format'), ('SMTP_REJECTED', 'Address rejected by mail server'), ('SMTP_ERROR', 'Mail server connection failure'), ('RATE_LIMITED', 'Daily sending limit reached'), ('PROVIDER_ERROR', 'Email provider error'), ('UNKNOWN', 'Unknown delivery failure')], default='', help_text='Machine-readable reason for invitation failure.', max_length=30),
        ),
    ]
