# Generated by Django 5.2.11 on 2026-03-01 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_add_voter_access_request'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='voteraccessrequest',
            new_name='voting_vote_electio_859152_idx',
            old_name='voting_voter_election_c0bbe6_idx',
        ),
    ]
