# Generated by Django 5.2.11 on 2026-02-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='secret',
            field=models.CharField(blank=True, default='', help_text='Shared secret for HMAC-SHA256 signature verification (strongly recommended)', max_length=128),
        ),
    ]
