# Generated by Django 5.2.11 on 2026-02-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_webhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='provider',
            field=models.CharField(blank=True, choices=[('brevo', 'Brevo'), ('azure', 'Azure Communication Services'), ('smtp', 'SMTP'), ('console', 'Console (dev)')], default='', help_text='Email provider used to send this message.', max_length=10),
        ),
    ]
